#!/bin/bash
# Commands Reference - Commandes Rapides

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   Hotel Reservation System - Commandes Rapides               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 LOCALISATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
pwd
echo ""

echo "🚀 DÉMARRAGE - OPTION 1 (Auto - Windows)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "start.bat"
echo ""

echo "🚀 DÉMARRAGE - OPTION 2 (Manuel)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Terminal 1 - Frontend:"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "Terminal 2 - Backend:"
echo "  cd backend"
echo "  npm install"
echo "  npm run dev"
echo ""

echo "🌐 ACCÈS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Frontend:  http://localhost:5173"
echo "Backend:   http://localhost:5000"
echo "API Test:  http://localhost:5000/api/hotels"
echo ""

echo "📝 COMMANDES UTILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Frontend:"
echo "  npm run dev       Lancer développement"
echo "  npm run build     Build pour production"
echo "  npm run preview   Préview du build"
echo ""
echo "Backend:"
echo "  npm run dev       Lancer avec nodemon"
echo "  npm start         Lancer en production"
echo "  npm test          Lancer tests (si définis)"
echo ""
echo "Général:"
echo "  npm install       Installer dépendances"
echo "  npm audit         Vérifier sécurité"
echo "  npm list          Lister dépendances"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "INDEX.md             📚 Index complet de la doc"
echo "QUICK_START.md       ⚡ Démarrage ultra-rapide"
echo "README.md            📖 Vue d'ensemble"
echo "GETTING_STARTED.md   🚀 Installation complète"
echo "ARCHITECTURE.md      🏗️  Structure du code"
echo "NAVIGATION_GUIDE.md  🗺️  Guide des pages"
echo "FINAL_SUMMARY.md     ✨ Résumé final"
echo "DEPLOYMENT.md        🌐 Déploiement production"
echo "CHECKLIST.md         ✅ État du projet"
echo ""

echo "🧪 TEST RAPIDE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Tester l'API (après démarrage du backend):"
echo ""
echo "  curl http://localhost:5000/api/hotels"
echo ""
echo "Ou avec jq (formaté):"
echo "  curl http://localhost:5000/api/hotels | jq"
echo ""

echo "🎯 FLUX DE TEST RECOMMANDÉ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Lancer: npm run dev (frontend)"
echo "2. Lancer: cd backend && npm run dev (backend)"
echo "3. Aller à: http://localhost:5173"
echo "4. Voir la liste d'hôtels"
echo "5. Cliquer sur un hôtel"
echo "6. Essayer une réservation"
echo "7. Aller à: http://localhost:5173/#admin"
echo "8. Voir le panel admin"
echo ""

echo "🔧 DÉPANNAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Port 5173 déjà utilisé?"
echo "  Changer dans vite.config.js: port: 5174"
echo ""
echo "Port 5000 déjà utilisé?"
echo "  Changer dans backend/.env: PORT=3001"
echo ""
echo "node_modules corrompu?"
echo "  rm -rf node_modules && npm install"
echo ""
echo "Cache npm?"
echo "  npm cache clean --force"
echo ""

echo "⭐ POINTS CLÉS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Frontend: Vite (ultra-rapide)"
echo "✓ Backend: Express (robuste)"
echo "✓ Auth: JWT + bcrypt (sécurisé)"
echo "✓ API: RESTful complète"
echo "✓ Docs: Exhaustive et claire"
echo "✓ Prêt: Production et concours"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    Bon développement! 🚀                      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
